apiVersion: almc.applicationmgr.io/v1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: applicationmgr
    app.kubernetes.io/managed-by: kustomize
  name: application-nginx
spec:
  image:
    repository: nginx
    tag: "latest"
  service:
    port: 80
  ingress:
    hosts:
      - host: example.local
        paths:
          - path: /
  healthcheck: "/"
